### ISSUE TITLE
Copula in UD v2

### ISSUE THREAD

**Issue by manning** [UniversalDependencies/UD_v2#15] opened 2016-09-28 03:58 UTC
My thoughts reading through:
- The current UD English differentiates the existential "there is" from noun _be_ predicate cases, which are mainly equational or predicative, though arguably some of them can also be existential like the given example of "A book is on the table." I could live with moving to the "consistently predicative" analysis suggested here for examples 11 and 13. However, I'm not totally convinced that it is better than what we now have. Some facts - such as the Swedish (or Spanish) facts right below where a different verb is used for existentials - do give some credence to doing the opposite. The change might make English annotation easier and more consistent, but it reduces cross-linguistic parallelism between at least English and Swedish.
- I would defer to Romance native speakers, but I'm not quite sure that it is the right decision for Portuguese, Spanish, and Catalan to have only _ser_ as `cop`. I would have been tempted to say that they have two copulas and mark both _ser_ and _estar_ as `cop`. If we don't do so, it seems like many constructions of transient state that would be a `cop` in English like "He is tired" / "Él está cansado.", "He is crazy" / "Él está demente." would then be non-parallel as non-copula constructions in Spanish, etc.
- Copula with clausal predicate. I think I pointed out to Sebastian the "To discuss" case in 17. I've never been happy with the inconsistent headship that we have used for these clausal predicate cases in the past, and so a better solution would be good! But, nevertheless, I've also thought that a very good property is that we can tell where a clause boundary occurs in a dependency tree, and with this proposed representation, we seem to lose that, completely for 17 and somewhat for 16 (since I'd see the embedded clause as "to be capable of thinking one's own thoughts", not including the "is" that is also "cop"). We could fix at least 17 by instead having a relation like _nsubj:ext_ for "external subject", but then we lose reusing the nsubj:cop, which some seem to think useful, and the two `cop` are still not really differentiated.

Copulas are difficult!

**Comment by jnivre** [comment] 2016-11-16 19:03
We need to resolve the treatment of nonverbal predication (aka copula constructions or nominal sentences). As you all know, there are two fundamental questions that we need to answer here:

1. In which constructions do we treat a nonverbal element (nominal, adjective, prepositional phrase, clause) as the main predicate (root) of a clause?
2. Which verbs can occur as a copula (cop) in one of these constructions?

With regard to 2, there seems to be a consensus that we should be maximally restrictive and only allow verbs that do not add any semantic content except tense-mood-aspect. This means that most languages will have at most one copula verb, but a few may have more than one because of defective paradigms (Turkish) or aspectual distinctions (Spanish). I will therefore regard this as settled and concentrate on question 1.

After consulting a wide array of linguistic papers, mostly with a typological slant, I have categorized the relevant constructions into the following major types:

1. Equation: “she is my mother”
2. Attribution: “she is nice”
3. Location: “she is in the bathroom”
4. Possession: “the book is hers”
5. Benefaction: “the book is for her”
6. Existence: “there is food”

Some of the categories have important special cases:

1b. Equation where (at least) one of the equated elements has clausal form: “the problem is that we don’t know how to analyze nonverbal predication”
4b. Possession that would be translated into English as “she has a book” but literally is more like: “a book is to-her” (cf. also 5)
6b. Existence with a location modifier: “there is food in the kitchen”

Categories 1 and 2 are unproblematic (except for 1b, which I will return to later) and we all agree that, in order to capture parallelism across languages, we should treat the nonverbal predicate (“mother”, “nice”) as the root of the clause and the other core argument (“she”) as the subject of this predicate (using “nsubj” or “nsubj:cop”). Some languages will in addition have a verbal copula (“is”), which will be attached to the predicate with the “cop” relation; other languages will have a nonverbal copula analyzed in the same way; and yet other languages will have no copula at all (either optionally or obligatorily). So far so good.

Category 3 (Location) has been discussed a lot, and some of us strongly object to treating “in the bathroom” as a predicate, but in the interest of parallelism it seems that we should treat this category just like 1 and 2 (which is also the current proposal). Languages that do not use a copula (or omits it in certain tenses) generally do not make a distinction between 1-2 and 3. This is true (I believe) of Slavic and Semitic languages, and it seems to be true of all the more exotic languages that I have seen discussed in the typological literature as well (mostly Australian languages). Hence, it seems we have little to gain (except obedience to the traditional European grammar tradition) but a lot to lose by not treating this category as a case of nonverbal predication.

Categories 4 (Possession) and 5 (Benefaction) have hardly been discussed at all and maybe are not problematic. I assume they should be included as long as it is clear that the verb used is the normal copula verb (or nothing) and not a different verb like “have” and as long as it is clear that the possessor or benefactive is not the grammatical subject. However, it would be interesting to know whether these cases group with 1-3 in languages that regularly omit the copula. What about Slavic and Semitic languages, for example? 

Category 6 (Existence) has only been discussed in the special case (6b) where it has a location modifier. The current v2 draft says that 6b should be grouped with the other cases of nonverbal predication but I now think that this is a mistake (as Chris has argued all along). The one advantage of doing this is that we get a parallelism between 6b and 3, but this has to be weighed against the following three counter-arguments:

(a) We lose parallelism between 6 and 6b (because the verb has to be the root in the former).
(b) We lose parallelism with a number of languages, not only Swedish and Romance languages, which use different verbs, but also Hebrew (if I interpreted Reut's comment correctly) and most of the languages discussed in the typological literature, which do not have verbless constructions here even if they do in all the others.
(c) There is other evidence suggesting that 6b, unlike 3, is not a case of predication. For example, 6b does not allow definite noun phrases. A sentence like “there is the food in the kitchen” is weird (unless “in the kitchen” attaches to food, in which case it is 6 and not 6b). This strongly suggests that we should care more for the parallelism between 6 and 6b than between 6b and 3.

Summing up, my proposal so far is that we should modify the v2 draft by excluding existential constructions altogether and treat the verb as the root in both 6 and 6b. 

This leaves us with the special case 1b, which is a real corner case. On the one hand, it seems to be a case of Equation, which suggests that the verb should not be treated as the root. On the other hand, treating the clause as the root completely messes up the clause boundaries and assigns two subjects to the clausal predicate (and sometimes also two copulas). Using the subtype nsubj:cop doesn’t really fix this problem, as is clearly shown by Fran’s discussion in the v2 draft. Unless we want to introduce completely new relations to handle this case, I think the least evil solution is to maintain the v1 analysis and treat the (copula) verb as the root. Being able to identify clauses is a very important requirement for linguistic analysis, parsing and downstream applications alike, so I would invoke Manning’s Law here and say that it is better overall than trying to save the parallelism between 1 and 1b at all costs. It is not a perfect solution, but I now think that it is the best solution we can achieve without introducing new representational devices.

Finally, I would like to question the value of the new subtype nsubj:cop. If we agree that it doesn’t solve the problem posed by 1b (except occasionally by accident), then the motivation for this subtype is not so string. It is true that it allows us to distinguish subjects of verbal and nonverbal predicates, but this would then be the only such distinction we make. For example, we do not distinguish subjects of intransitive and transitive predicates (which many language typologists would argue is equally important). I don’t have a very strong preference here, but I think the issue deserves revisiting.

**Comment by ftyers** [comment] 2016-11-16 19:54
I'm not sure if this is directly relevant to the argument, but although definite complements often sound weird without context in English, they don't sound nearly so bad in context:

From Wikipedia:
```
There are two world championship competitions that Canada 
  participates in. There is the ICU World Championships where 
  the National Teams compete against each other and 
  then there are the Club team World Championships. 
There is the widespread use of "promotional consideration", in which 
  a game show receives a subsidy from an advertiser in return 
  for awarding that manufacturer's product as a prize or consolation prize.
In addition, there are the opportunity cost of those who 
  forgo the use of spam-afflicted systems. There are the direct costs, 
  as well as the indirect costs borne by the victims.
There are the following special cases: ... 
```

I agree with the treatment of 1, 2, 3.

Regarding (4) at least for Russian, this groups with (6). 
```
У меня (есть) книга
In me (there.is) book.
```

Then questions:

1) Do we have any numbers for how many languages have existential constructions with bare copula (e.g. Czech, Finnish, English, Russian), how many have a verb (e.g. Swedish, Romance), and how many have non-verbal (e.g. adjective/pronoun) with copula (e.g. Turkic)?  

2) Does this mean that in Finnish we will get a different head for "On kirja pöydässä." (There is a book on the table) and "Kirja on pöydässä." (The book is on the table) ?  [The word order difference is a bit artificial] 

In general, I think that, given the shortage of time, the proposal is a solid incremental improvement. However, I do have the feeling that it will be revisited when we have more data. 

PS. Do you have a list of the papers you read ? (I have a number of references, but would be interested in reading more)

**Comment by jnivre** [comment] 2016-11-16 23:12
@ftyers When you say that 4 groups with 6 in Russia, do you mean that both should be excluded or that both should be included. Is the optional verb the same as in 1-3. In the end, we may have to opt for a solution where 1-3 are included in all languages, while 4-6 are subject to language-specific variation depending on whether they use the same verb (or absence of verb) as 1-3.

Ad 1: I don't think we have these numbers, and I am not sure how we could get them, given that there is no treebank query that identifies existential constructions. Or is there?

Ad 2: Yes, I think so. But it depends on whether they are identifiable as distinct constructions (as I think there English translations are). One of the main points of the revised proposal is that we want to have the same head in "There is food" and "There is food on the table". How do you say "There is food" in Finnish?

Here is a partial list of papers/book chapters that I read or skimmed:

Curnow, Timothy Jowan 2000. Towards a cross-linguistic typology of copula constructions. Henderson, John (ed.), Proceedings of the 1999 Conference of the Australian Linguistic Society. http://www.linguistics.uwa.edu.au/__data/page/73643/curnow.pdf.

Dixon, R.M.W. 2002. Copula clauses in Australian languages: A typological perspective. Anthropological Linguistics 44(1). 1-36.

McKay, Graham. 2010. Relational, Copula and Verbless Clauses in Rembarrnga. In Yvonne Treis & Rik De Busser (eds.), Selected Papers from the 2009 Conference of the Australian Linguistic Society. http://www.als.asn.au/proceedings/als2009/mckay.pdf.

**Comment by ftyers** [comment] 2016-11-16 23:55
I think that for all of (3), (4b), (6), and (6b) in Russian and Finnish the copula verb (olla, быть) should be treated as `cop`.  

3) The book is on the table.
Книга на столе .         [lit.  book on table]
Kirja on pöydällä .       [lit. is book on.table] **

4b) I have a book.
У меня (есть) книга .  [lit. at me (there.is) book]
Mulla on kirja .            [lit. on.me is book]

5) There is a book.
Есть книга .                [lit. there.is book]
Kirja on .                     [lit. book is]  ***

6b) There is a book on the table.
Есть книга на столе .   [lit. (there.is) book on table]    {or}
На столе (есть) книга . [lit. on table (there.is) book]
On kirja pöydällä .         [lit. is book on.table] **

I agree that we want to have the same head in "There is food" and "There is food on the table", but I think that the head should be food. To distinguish the attachment we have `nmod` and `obl`.

Regarding the numbers, I think there is no way aside from looking up in the literature for each language how existentials are done, and then looking for examples of each category in the individual treebanks. It's been something I have been meaning to do. In drafting the proposal I tried to get a representative sample, but I think it would be much more convincing with an exhaustive sample.

I think that having 1--3 as universal and 4--5 as permitting language-specific variation is a good stop-gap measure. In any case, I think for (1b) we need to keep the copula as root, at least for this cycle.

** These are technically ambiguous (at least in translation) between "There is a book on the table", "A book is on the table" and "The table has a book".
*** Technically ambiguous (at least in translation) between "It is a book" and "There is a book".

**Comment by jnivre** [comment] 2016-11-17 05:54
Do you really think "book" should be the root in "there is a book (on the table)"? Also in English? But then these will still not be parallel to "the book is on the table", where "table" is the root. 

The copula is a verb (or other element) linking a nonverbal predicate to its subject, but there is no subject in "there is a book" if you treat "book" as a predicate, so in what sense is "is" a copula then?

**Comment by ftyers** [comment] 2016-11-17 09:59
@jnivre No, disregard that specific sentence. I should have been more careful in posting. 

Looking at the data again:

```
3) The book is on the table.                              [head is 'table']
Книга на столе . [lit. book on table]                  [head is 'столе']
Kirja on pöydällä . [lit. is book on.table] **        [head is 'pöydällä']

4b) I have a book.
У меня есть книга . [lit. at me there.is book]    [head is 'есть']
У меня  книга . [lit. at me book]                        [head is 'меня' --- promotion]
Mulla on kirja . [lit. on.me is book]                    [head is 'on' --- "I have a book"]
                                                                        [head is 'mulla' --- "The book is on me."]

5) There is a book.                                         
Есть книга . [lit. there.is book]                          [head is 'Есть']
Kirja on . [lit. book is] ***                                   [head is 'on' -- "There is a book"]
                                                                         [head is 'kirja' -- "It is a book"]

6b) There is a book on the table.
Есть книга на столе . [lit. (there.is) book on table] {or}    [head is 'Есть']
На столе книга . [lit. on table (there.is) book]                  [head is 'столе' --- promotion]    
On kirja pöydällä . [lit. is book on.table] **                       [head is 'on' -- "There is a book on the table"]
                                                                                        [head is 'pöydällä' --- "The book is on the table"]
                                                                                       [head is 'on' --- "The table has a book"]
```

I think the issue in Finnish is that there is no special "existential" construction, so we have to either make a distinction that isn't there (apart from maybe in discourse/semantics) or we pick one way of doing it. 

It's worth noting that I feel like I'm just confusing the matter more than solving any problems at the moment. 

Do you think that it would be worthwhile making a table and doing some counts of how often construction [1, 2, 3, 4, 4b, 5, 6, 6b] is used with strategy ['copula', 'zero copula', 'have verb', 'pronoun', ...] in the treebanks ?

**Comment by dan-zeman** [comment] 2016-11-17 12:47
Thanks @jnivre for the overview. I think this proposal is an improvement, except for the existential bit (6/6b), which I disagree with. Czech is one of the languages that use the same verb for copula and for existence (although for existence you could also use another verb, the loanword _existovat_), and the existential meaning can be only derived from topic-focus articulation, i.e. from word order:

* _Jídlo je / Je jídlo / Jídlo existuje / Existuje jídlo_ lit. "Food is / Is food / Food exists / Exists food" = "There is food"
* _Na stole je jídlo_ lit. "On table is food" = "There is food on the table" (but this word order could be also a response to _Kde je jídlo?_ "Where is the food?" and it would be no longer existential)
* _Jídlo je na stole_ lit. "Food is on table" = "(The) food is on the table" (more probably location than existence)

I would fight to be able to use the same analysis for the second and the third example. I think the "there-construction" is English-specific and should not be generalized to existential constructions in other languages. (But from my point of view, it would be quite OK to make "there" the predicate in "There is a book".) In the first example, we have no location available as predicate and we have to promote the verb to the root position. (But such examples—locationless existential—will be rare.)

**Comment by jnivre** [comment] 2016-11-17 16:39
@ftyers If there is no distinction in Finnish, then maybe 6b simply does not exist, which is totally fine, of course. 

The distinction we are trying to make is that between a topic-comment structure (the book is on the table) and what William Croft calls a thetic structure (there is a book on the table). Only the former involves nonverbal predication (according to him).

**Comment by jnivre** [comment] 2016-11-17 16:46
@dan-zeman The topic-comment (or topic-focus) articulation is precisely what distinguishes the two cases. But I completely understand your instinct to fight, as there is no formal distinction in Czech (as there is in English).

Perhaps we can get away with claiming that there is no grammaticalised distinction between 3 and 6b in either Czech or Finnish and that they will therefore be grouped together as an instance of 3. For 6, I assume you want the verb as root, don't you? I guess this could be seen as a case of promotion, though.

**Comment by dan-zeman** [comment] 2016-11-17 19:55
Yes, if 6 is seen as excluding 6b and if it is Czech, then the verb is root and there are no other possibilities anyway.

**Comment by tlynn747** [comment] 2016-11-18 12:31
Hi All,

I hope you don’t mind my input here. This copula discussion affects the Irish UD Treebank significantly, so I though it might be worth chipping in an Irish linguistic perspective.

We have two verbs “to be” in Irish. One is the copula, the other is a Substantive (Subs) verb _bí_ “to be”. As @ftyers alluded to already, there are different rules as to when and how either should be used. I’ll start by translating 1-6 and indicating which form is used for each:

1. Equation (COP)
_Is      ise  mo mháthair_  
COP  her my mother
She is my mother


2. Attribution (Subs)
_Tá sí deas_  
Be she nice
She is nice

3. Location (Subs)
_Tá sí sa seomra folctha_ 
Be she in room bath
She is in the bathroom

4. Possession  (Cop)
_Is lei an leabhar_ 
COP with-her the book
The book is hers
 
5. Benefaction (Cop)
_Is di an leabhar_ 
COP for-her the book
The book is for her

6. Existence (Subs)
_Tá bia ann_ 
Be food there  
(food is there)

1b. Copula use
_Is é an fadhb ná nach bhfuil a fhios againn conas is féidir ainilís a dhéanamh ar an “nonverbal predication_”
 “the problem is that we don’t know how to analyze nonverbal predication”

6b. Substantive use
_Tá bia sa chistin_
Be food in-the kitchen
“there is food in the kitchen”


Differences between the Irish copula and substantive verb _bí_ “to be”.
-	the copula can be dropped, _bí_ can’t
-	the syntax order is different:
        COP-Predicate-Subject vs 
        Subs-Subject-Predicate**
-	the substantive verb inflects for tense, aspect, person, number – just as any other VERB 
The copula has 2 tensed forms: present/ future and past/conditional
-	Clefting (fronting) is widespread in Irish and uses the copula (not the substantive verb)


In addition, there are many other uses of the substantive verb _bí_ in Irish that aren’t summarised here. For example:

Progressive aspectual:
_Tá sé ag imeacht_
Be he at leaving (VerbalNoun)
He is leaving

Emotions:
_Tá brón orm_
Be sorrow on-me
I am sorry

State of being:
_Tá slaighdéan orm_
Be a cold on-me
I have a cold

_Tá leabhar uaim_
Be a book from-me
I want a book

_Tá duine eile i mbun peannaireacht_
Be person else in charge writing
Someone else is in charge of writing

_Orm/ uaim_  are inflected prepositions. There are 16 prepositions that inflect like this and can form idiomatic type phrases such as these examples. It should be noted, however, that it’s not flowery idiomatic language that is only used in literary terms. This is standard syntax.
There is no other way of saying “I am sorry” or “I have a cold”, and no other option for creating the progressive aspect, aside from using the verb “to be”. 

Our argument is to allow for us to treat the substantive verb as a verb and not as a copula. This way sentence structures with regular verbs and substantive verbs are all treated the same.
We introduced a a language specific label _xcomp:pred_ for use in some of the substantive verb examples. See our description [here](http://universaldependencies.org/ga/dep/all.html#al-ga-dep/xcomp:pred): 

Happy to answer more questions on how we differentiate between the copula and the substantive. Our copula analysis description is [here](http://universaldependencies.org/ga/dep/all.html#al-ga-dep/cop)
 The [link](http://nualeargais.ie/gnag/kopul2.htm) that @ftyers provided is helpful, although I don’t agree with the existence discussion per se!

We completely understand that the aim is to achieve parallelism, and have adjusted many of our analyses to that end. And it is always the case that detail for one language could be lost to the benefit to another, that's inevitable. However, we also believe (and from our Uppsala discussion) and this insight into the two different treatments might actually benefit many other languages across the board.  



** The equation example may look like the order follows: Cop-Subj-Pred, when it is in fact Cop-Pred-Subj

_Is ise mo mháthair_
COP her my mother
She is my mother

In fact, these equations (classificatory) constructions read "my mother is her". The nominal form of she is _si_, the accusative form is _i_, and in this case it has an emphatic suffix _-se_.

**Comment by jnivre** [comment] 2016-11-18 14:51
We most definitely don't mind. On the contrary, this is extremely useful, even though it seems that you blew my current theory to bits. :)

I was starting to think that we could treat 1-3 as uniform across languages and allow language-specific variation in 4-6, based on whether they use the same verb (or nonverb or nothing) as in 1-3. But it seems that, for Irish, the natural grouping is 1+4+5 against 2+3+6.

**Comment by manning** [comment] 2016-11-21 20:24
I don't have a lot of smart things to say, but two comments, one on Modern Irish, and then a general proposal.

**Modern Irish:** – @tlynn747 can correct me when I goof up – I think it is relevant to emphasize that Modern Irish has a permanent/temporary (or stage-level vs. individual-level) predicate distinction, which I think is similar to Romance _ser/estar_:

Is dochtúir é Seán
COP doctor he/AGR Sean
'Sean is a doctor'

Tá Seán ina dhochtúir
Be Sean in-his doctor
'Sean is being a doctor.'

So if you follow a dictate of "be consistent with Irish" then that would go against what I wrote before for the treatment of _ser/estar_. Though I'm still not quite sure what to think in the Romance case.

Indeed, although not productive, a few permanent state  adjectives can appear with COP, so the description in 2. above is the general case but not quite the whole story:

Is greannmhar thú
COP funny you(ACC)
'You are funny.'

**General proposal:** For what to do in general for UD, I see no better general solution at present than to suggest the following:

1. If there is an overt word which is used for linking in equational (also known as definitional) sentences and/or between a subject and a predicate of semi-permanent state or quality, then that word is treated as a copula and marked with the cop dependency, and is not the head of the clause.
2. If there is an overt word which is used as a predicate of existence, either a different lemma, or with different syntax than in 1., then it should be regarded as being the head of existence clauses, taking a subj (and often a locative obl).
3. All other cases of putative copula constructions should be assimilated to cases 1. and 2. as seems to make most sense according to the inherent logic of the language concerned. One weird corner case is when equations are made between clauses, where it may prove better to use the analysis in 2., since otherwise there are analytic problems (getting 2 subjects that cannot be distinguished) and an analysis like 1. suffers from losing the ability to easily partition a sentence into clauses.

Under these proposed rules, I think that English could (and should) be analyzed just as @jnivre proposed and Modern Irish can be analyzed just as @tlynn747 proposed!

**Comment by jnivre** [comment] 2016-11-21 20:46
I think the general proposal by @manning sums it up very well. It provides general guidelines and promotes parallelism while allowing language-specific variation when clearly motivated. I think it is the best we can do for v2 (and possibly forever). I also think we should use analysis 2 when equations are made between clauses. I am tempted to close this issue quickly before anyone comes up with an objection. :)

**Comment by ftyers** [comment] 2016-11-21 21:09
Agree with @jnivre that this is the best we can do for v2, although hold out hope for forever/tomorrow. :)

**Comment by tlynn747** [comment] 2016-11-22 14:31
Thanks for the input @manning, this really helps. Although I'd be interested in knowing where the example "Is greannmhar thú" came from as it's ungrammatical! Email is probably best however, as I agree with @jnivre that it's best to close this issue out quickly :)

On an aside, @ftyers and I were talking about writing a paper on this, as it's such an interesting issue and the copula was a significant consideration in my PhD work, treebank design. Any other interested parties are welcome! 

Best of luck with the new guidelines release 👍

**Comment by jnivre** [comment] 2016-11-22 15:51
Hi Teresa,

A paper about this sounds like an excellent contribution to the first UD workshop in Gothenburg in May. :)

Joakim

On 22 Nov 2016, at 15:31, Teresa Lynn <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the input @manning<https://github.com/manning>, this really helps. Although I'd be interested in knowing where the example "Is greannmhar thú" came from as it's ungrammatical! Email is probably best however, as I agree with @jnivre<https://github.com/jnivre> that it's best to close this issue out quickly :)

On an aside, @ftyers<https://github.com/ftyers> and I were talking about writing a paper on this, as it's such an interesting issue and the copula was a significant consideration in my PhD work, treebank design. Any other interested parties are welcome!

Best of luck with the new guidelines release 👍

**Comment by ftyers** [comment] 2016-11-22 16:11
FYI: I'm collecting example sentences in a Google spreadsheet from all of the UD treebanks follow Joakim's categories above. I've got 109 so far... which is about 1/4 of the examples necessary to cover all languages * all constructions. If anyone else would like access ping me with your Google account.

**Comment by fginter** [comment] 2016-11-23 08:18
If you guys need a Finn or two with opinions on copulas - and especially someone who can help you gather examples and statistics across corpora with dep_search, we are happy to join. @fginter @jmnybl

**Comment by dan-zeman** [comment] 2016-11-23 09:13
Seen the spreadsheet, got interested :-)

**Comment by manning** [comment] 2016-11-25 01:01
The data from WALS is also highly relevant.

This chapter shows whether nominal and locational predication is done with the same strategy: http://wals.info/chapter/119 . There are over twice as many languages which use 2 different strategies (words) here as languages that use the same copula for both (as in English). So different is actually the common case. So, the UD decision we should make is: If these two things are done by different mechanisms, is only the former marked cop? (That seems to have been the way people have been voting for Irish and Spanish.) This would sort of fit well in that it is only the nominal predication usage that frequently allows zero copula.

For zero copulas: http://wals.info/chapter/120 . It seems like they are possible in close to half the world's languages, and both languages with and without sometimes zero copulas are very widely distributed across the globe. So zero copulas definitely isn't just a handful of languages.

**Comment by ftyers** [comment] 2016-11-25 09:40
@manning Yes, I think only the former should be marked cop. There also seems to be a lot less variation in how nominal predication is done (at least in the current UD languages).

My feeling currently is: The mechanism for (1) should be marked `cop`. Other constructions 2,3 that use the same strategy should also be `cop`, but if they use different strategies then

**Comment by ftyers** [comment] 2016-11-25 09:42
Sorry for the inbox spam, hit the wrong button. Will be back after coffee with a comment. :)

**Comment by jnivre** [comment] 2016-11-27 16:01
I have now updated https://turkunlp.github.io/docs/v2/copula.html to reflect the recent consensus.

@manning @ftyers @dan-zeman @tlynn747 Please check that what we are saying about different languages are correct, and please (re)add examples for Russian, Finnish and Turkish if you have time.

I am now closing this issue.

**Closed by jnivre** 2016-11-27 16:01 UTC

**Comment by jnivre** [comment] 2016-11-28 20:17
Excellent! Please feel free to reformulate to avoid the implication of fixed word order. I only meant to refer to the English examples, and it would be unfortunate if this gave the wrong impression.

**Comment by dan-zeman** [comment] 2016-11-29 09:11
Done.

**Comment by ftyers** [comment] 2016-11-29 10:03
I added the examples for Turkish and created a pull request (I don't seem to have direct commit access).

**Comment by tlynn747** [comment] 2016-11-29 11:50
That's great @dan-zeman ... The Irish order is Copula-Predicate-Subject (for the cop label use)

I'll try to get around to fixing the examples provided later today to reflect this.
